const courses = [
    {
        imgsrc:"https://www.codewithharry.com/img/notes/c.webp",
        name:"C",
        href:"https://www.youtube.com/playlist?list=PL7Xm-HsLEy4xZpA2uI-jyxc9X9KZSPiqi"
    },
    {
        imgsrc:"https://www.codewithharry.com/img/notes/cpp.webp",
        name:"C++",
        href:"https://youtube.com/playlist?list=PL7Xm-HsLEy4x4iWGJ3rMbDbfiTDo7izhy"
    },
    {
        imgsrc:"https://www.codewithharry.com/img/notes/java.webp",
        name:"java",
        href:"https://youtube.com/playlist?list=PL7Xm-HsLEy4wDCmZOtsBilxChD8lL6NEl"
    },
    {
        imgsrc:"https://www.codewithharry.com/img/notes/python.webp",
        name:"python",
        href:"https://youtube.com/playlist?list=PL7Xm-HsLEy4wpSh926XL6PMbyJ3_Mtao2"
    },
    {
        imgsrc:"https://www.codewithharry.com/img/notes/html.webp",
        name:"html",
        href:"https://youtube.com/playlist?list=PL7Xm-HsLEy4z_Jaf740zhvIwKSCNifhrB"
    },
    {
        imgsrc:"https://www.codewithharry.com/img/notes/css.webp",
        name:"css",
        href:"https://youtube.com/playlist?list=PL7Xm-HsLEy4z_Jaf740zhvIwKSCNifhrB"
    },
    {
        imgsrc:"https://www.codewithharry.com/img/notes/js.webp",
        name:"javascript",
        href:"https://www.youtube.com/playlist?list=PL7Xm-HsLEy4xVvqdhphXfCr2uZIwRdJ5r"
    },
    {
        imgsrc:"https://www.codewithharry.com/img/notes/reactjs.webp",
        name:"React",
        href:"https://www.youtube.com/playlist?list=PL7Xm-HsLEy4xVvqdhphXfCr2uZIwRdJ5r"
    },

]
export default courses